### ISSUE TITLE
Cannot open settings, and sudo ldconfig did not help or fix it.

### ISSUE THREAD

**Issue by nickolasio** [pop-os/gnome-control-center#131] opened 2020-11-30 12:15 UTC
https://imgur.com/a/oyCLy54 (Image of the terminal output)

Terminal output:

```
nico@pop-os:~$ sudo gnome-control-center
[sudo] password for nico: 
gnome-control-center: error while loading shared libraries: **libpop_upgrade_gtk.so.0**: cannot open shared object file: No such file or directory
nico@pop-os:~$ 
```

Yes I did do my research on this, no luck as of now, and `sudo ldconfig` did not fix this, and rebooting didn't fix it either, even after running `sudo ldconfig`.

**Comment by ids1024** [comment] 2020-11-30 14:49
Hm, strange the same command didn't fix it. What's the output of `apt policy libpop-upgrade-gtk` and `echo /usr/lib/libpop_upgrade_gtk*`?

**Comment by scarter88** [comment] 2020-11-30 17:00
> Hm, strange the same command didn't fix it. What's the output of `apt policy libpop-upgrade-gtk` and `echo /usr/lib/libpop_upgrade_gtk*`?

I've got the same issue, same output as @nickolasio has in his terminal output.
Here's the output requested from @ids1024 'apt policy libpop-upgrade-gtk'

`libpop-upgrade-gtk:
  Installed: 0.1.0~1603472643~20.04~05600dc
  Candidate: 0.1.0~1606240865~20.10~351ec93
  Version table:
     0.1.0~1606240865~20.10~351ec93 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
 *** 0.1.0~1603472643~20.04~05600dc 100
        100 /var/lib/dpkg/status
`
and the output for 'echo /usr/lib/libpop_upgrade_gtk*'

`/usr/lib/libpop_upgrade_gtk.so`

**Comment by jacobgkau** [comment] 2020-11-30 17:05
> `Installed: 0.1.0~1603472643~20.04~05600dc Candidate: 0.1.0~1606240865~20.10~351ec93`

The candidate is newer than the installed version, that means an update is available. If you install all updates, does Settings open? (You should be able to do that through the Pop Shop, or using `sudo apt full-upgrade`.)

**Comment by scarter88** [comment] 2020-11-30 17:09
When I attempt to update through pop shop, it shows it updates a single system update, and then just shows back up again as if it hasn't updated. When I update via terminal with sudo apt full-upgrade, I get the following:

`The following packages were automatically installed and are no longer required:
  gnome-shell-extension-desktop-icons libminiupnpc17 nvidia-driver-440 vino
Use 'sudo apt autoremove' to remove them.
The following packages have been kept back:
  libpop-upgrade-gtk pop-upgrade
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
 `
Thanks

**Comment by nickolasio** [comment] 2020-11-30 17:11
Sorry for the very late reply, I thought it was gonna be a few hour in between, I'll see this now

**Comment by nickolasio** [comment] 2020-11-30 17:16
Terminal output:
```
nico@pop-os:~$ apt policy libpop-upgrade-gtk
libpop-upgrade-gtk:
  Installed: 0.1.0~1588275436~20.04~ad9653c
  Candidate: 0.1.0~1606240865~20.04~351ec93
  Version table:
     0.1.0~1606240865~20.04~351ec93 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
 *** 0.1.0~1588275436~20.04~ad9653c 100
        100 /var/lib/dpkg/status
nico@pop-os:~$ echo /usr/lib/libpop_upgrade_gtk*
/usr/lib/libpop_upgrade_gtk.so
nico@pop-os:~$ 

```
I didn't want to update due to it being about almost 10gb in total of updates, so I'd really appreciate some way that doesn't involve updating everything, since I got about 2gb free on the main root partition.

**Comment by nickolasio** [comment] 2020-11-30 17:22
I have a theory on how to fix this, can someone provide me with a working `libpop_upgrade_gtk.so.0` file, that is either an older or newer version.

**Comment by nickolasio** [comment] 2020-11-30 17:25
`sudo apt install libpop-upgrade-gtk`
I ran this command it works fine now.

**Comment by nickolasio** [comment] 2020-11-30 17:26
Thanks for the help either way,
I appreciate you people went of your way to help : )

**Comment by scarter88** [comment] 2020-11-30 17:28
> `sudo apt install libpop-upgrade-gtk`

I get the following when running this. Can someone please advise? Thanks

`The following packages have unmet dependencies:
 libpop-upgrade-gtk : Depends: pop-upgrade (= 0.1.0~1606240865~20.10~351ec93) but 0.1.0~1603472643~20.04~05600dc is to be installed
E: Unable to correct problems, you have held broken packages.`

**Comment by ids1024** [comment] 2020-11-30 17:31
@scarter88 If you don't have any reason to do otherwise, just doing `apt update` followed by a full `apt upgrade` is more reliable than trying to upgrade individual packages.

**Comment by scarter88** [comment] 2020-11-30 17:35
> @scarter88 If you don't have any reason to do otherwise, just doing `apt update` followed by a full `apt upgrade` is more reliable than trying to upgrade individual packages.

on doing a apt update && apt upgrade I get the following:

`The following packages have been kept back:
  libpop-upgrade-gtk pop-upgrade
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.`

**Comment by ids1024** [comment] 2020-11-30 17:47
I don't like how `apt` doesn't state why packages have been "kept back".

How about `sudo apt --with-new-pkgs upgrade`? That should help with some cases where packages are kept back. I'm not sure exactly what the issue is in this case.

**Comment by scarter88** [comment] 2020-11-30 18:17
I get the same exact message using --with-new-pkgs.

**Comment by scarter88** [comment] 2020-11-30 18:32
`sudo apt install pop-upgrade` seems to have done the trick. Not sure why I explicitly had to install this package, but 
this fixed the issue for me.

**Comment by ids1024** [comment] 2020-11-30 18:34
Good to hear that worked. But It would be good to have more information to try to fix whatever issue is causing this. Did running that command install/remove/upgrade any other packages?

**Comment by scarter88** [comment] 2020-11-30 18:36
Here's my output from the above command before I continued:

`The following additional packages will be installed:
  libpop-upgrade-gtk
The following held packages will be changed:
  pop-upgrade
The following packages will be upgraded:
  libpop-upgrade-gtk pop-upgrade
2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
`

**Comment by Luis4ever22** [comment] 2020-12-16 04:09
`sudo apt install pop-upgrade` solved the issue for me; this bug was driving me nuts!

**Closed as completed** 2021-05-27 20:43 UTC
