### ISSUE TITLE
Changing search location options in Settings leads to a Segfault

### ISSUE THREAD

**Issue by Roger-ZRZ** [pop-os/gnome-control-center#149] opened 2021-02-16 00:45 UTC
**Distribution (run `cat /etc/os-release`):**
PopOs 20.10
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
PopOs Settings, supposedly newest (everything updated from apt and pop_shop)

**Issue/Bug Description:**
Changing search location options in Settings leads to a Segfault

**Steps to reproduce (if you know):**
Go to Settings-Search-Search_Locations, toggle any switch; 
The settings app will crash, and Journelctl shows segfault, see below; 

**Expected behavior:**
It should not crash with segfault...

**Other Notes:**
Journelctl log: 
...
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh kernel: gnome-control-c[291373]: segfault at 7ffe8fc24e58 ip 00007f49458e3521 sp 00007ffe8fc24e50 error 6 in libgio-2.0.so.0.6600.1[7f49457da000+119000]
Feb 15 19:41:41 dt-ruizhezh kernel: Code: 0e ff ff ff 0f 1f 44 00 00 f3 0f 1e fa 41 57 41 56 41 55 41 54 55 53 48 81 ec 00 10 00 00 48 83 0c 24 00 48 81 ec 88 02 00 00 <89> 4c 24 08 49 89 d4 49 89 ff 49 89 f5 4c 89 44 24 10 4c 89 cd 64

**Comment by jacobgkau** [comment] 2021-02-16 15:40
I'm not able to replicate this on Pop!_OS 20.10. Can you please provide the output of this command to see which version of GNOME Control Center you have installed:

`apt policy gnome-control-center`

As well as a screenshot of what your search page looks like before you try to toggle any settings, to make sure I'm doing the same thing you are when trying to replicate?

**Comment by Roger-ZRZ** [comment] 2021-02-16 19:52
apt policy gnome-control-center
```
gnome-control-center:
  Installed: 1:3.38.3-1pop1~1610478558~20.10~d6f4dc1
  Candidate: 1:3.38.3-1pop1~1613417276~20.10~be09503
  Version table:
     1:3.38.3-1pop1~1613417276~20.10~be09503 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
 *** 1:3.38.3-1pop1~1610478558~20.10~d6f4dc1 100
        100 /var/lib/dpkg/status
     1:3.38.3-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy-updates/main amd64 Packages
     1:3.38.1-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/main amd64 Packages

```
Settings Pic: 
![Screenshot-20210216145021-1004x985](https://user-images.githubusercontent.com/33801496/108114151-6f3a5100-7066-11eb-8c96-ebc9fb815b0a.png)

**Comment by Roger-ZRZ** [comment] 2021-02-16 19:55
Toggle any switch in Step 3 (see pic) will result in segfault;

**Comment by ids1024** [comment] 2021-02-16 20:09
> ```gnome-control-center:
> Installed: 1:3.38.3-1pop1~1610478558~20.10~d6f4dc1
> Candidate: 1:3.38.3-1pop1~1613417276~20.10~be09503
> ```

That suggests there's an update available, though I don't think it should change anything related to this.

I don't see any crash or error toggling any of these (with version `1:3.38.3-1pop1~1613417276~20.10~be09503`):

![Screenshot from 2021-02-16 12-06-44](https://user-images.githubusercontent.com/2263150/108115783-743fd600-704f-11eb-83b0-aabcf3541e38.png)

Given not all of these seem to be showing for you, and the `g_file_get_path: assertion 'G_IS_FILE (file)' failed` errors, do all of these folders exist? I'm guessing something about the filesystem is confusing gnome-control-center.

**Comment by Roger-ZRZ** [comment] 2021-02-16 21:39
I deleted the other folders and changed `~/.config/user-dirs.dirs` (see below) so they do not show up in the sidebar; perhaps that led to the assertion failure? 

```
XDG_DESKTOP_DIR="$HOME/Desktop"
XDG_DOWNLOAD_DIR="$HOME/Downloads"
XDG_TEMPLATES_DIR="$HOME/Templates"
XDG_PUBLICSHARE_DIR="$HOME/Public"
XDG_DOCUMENTS_DIR="$HOME/Documents"
XDG_MUSIC_DIR="$HOME"
XDG_PICTURES_DIR="$HOME"
XDG_VIDEOS_DIR="$HOME"
```

Is it possible that a simple patch can make the selector not crash if some of the folders are deleted?

**Comment by ids1024** [comment] 2021-02-16 21:53
Ah, that file explains it. I was just looking at the [relevant code](https://github.com/pop-os/gnome-control-center/blob/master_focal/panels/search/cc-search-locations-dialog.c) and noticed that with the errors you were getting, `get_user_special_dir_if_not_home` must have been returning `NULL`.

It seems the current code in Gnome Control Center doesn't handle it properly when one of these directories is set to just `$HOME`.

This seems to be an upstream Gnome issue, and I'm really not sure why it's implemented the way it is, but it should be fixed. By making changes like that to `user-dirs.dirs` I'm able to reproduce it.

**Comment by Roger-ZRZ** [comment] 2021-02-16 23:16
Thanks!

**Comment by Roger-ZRZ** [comment] 2021-02-16 23:16
You can close the issue at your discretion, have a nice day!

**Comment by leviport** [comment] 2021-02-16 23:20
You too!

**Closed as completed by leviport** 2021-02-16 23:20 UTC
Labels: bug, upstream
