### ISSUE TITLE
Re-add fractional scaling controls

### ISSUE THREAD

**Issue by leviport** [pop-os/gnome-control-center#109] opened 2020-08-12 16:07 UTC
Once Ubuntu's xrandr scaling patch is fixed, we will re-add the controls

**Comment by jsco2t** [comment] 2020-08-24 14:57
A couple of questions:

1. I would be willing to test the linked fix for this issue. Even in beta format. Does `pop-os` need any beta/alpha testers here? (And if you need/want help testing are there steps I can follow to patch a live install with the fix?)

2. Is there an ETA on when the linked issue is expected to be merged?

3. I’m guessing this is being held up by the above mentioned `xrandr` bug in Ubuntu. Is there a link to that issue and it’s fix progress? Would be great to be able to keep an eye on what’s happening with the root cause issue. 

Thanks!

**Comment by mmstick** [comment] 2020-08-24 15:12
Active Launchpad bug report: https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/1892440

We're just waiting for Ubuntu to release a fix for their patch

**Comment by jsco2t** [comment] 2020-08-25 06:12
Thanks @mmstick - if you need any help testing the pop-os changes - just let me know. I appreciate all the hard work you and the team does!

**Closed as completed** 2020-10-05 18:42 UTC
